name: template
description: Template package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  data_table_2: ^2.5.15
  multiple_search_selection: ^2.7.0
  intl: ^0.19.0
  intl_utils: ^2.7.0
  animated_custom_dropdown: 3.1.1
  flutter_fancy_tree_view: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true