name: common_features
description: Common features package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  dio: ^5.4.0
  retrofit: ^4.0.3
  equatable: ^2.0.5
  curl_logger_dio_interceptor: ^1.0.0
  http_parser: ^4.0.2
  http: ^1.2.2
  logger: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner:
  retrofit_generator: